import { MediaItem, TVShow, Season } from "@/types/media";

export const MOCK_TRENDING_MOVIES: MediaItem[] = [
  {
    id: "movie-693134",
    tmdbId: 693134,
    imdbId: "tt15239678",
    type: "movie",
    title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    posterUrl: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s520b4q.jpg",
    releaseDate: "2024-03-01",
    year: 2024,
    rating: 8.2,
    voteCount: 4890,
    genres: [
      { id: 878, name: "Sci-Fi", slug: "sci-fi" },
      { id: 12, name: "Adventure", slug: "adventure" },
    ],
    runtime: 166,
    director: "Denis Villeneuve",
  },
  {
    id: "movie-1022789",
    tmdbId: 1022789,
    imdbId: "tt22022452",
    type: "movie",
    title: "Inside Out 2",
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions!",
    posterUrl: "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
    releaseDate: "2024-06-14",
    year: 2024,
    rating: 7.6,
    voteCount: 3950,
    genres: [
      { id: 16, name: "Animation", slug: "animation" },
      { id: 35, name: "Comedy", slug: "comedy" },
      { id: 10751, name: "Family", slug: "family" },
    ],
    runtime: 96,
  },
  {
    id: "movie-533535",
    tmdbId: 533535,
    imdbId: "tt6263850",
    type: "movie",
    title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    releaseDate: "2024-07-26",
    year: 2024,
    rating: 7.7,
    voteCount: 4200,
    genres: [
      { id: 28, name: "Action", slug: "action" },
      { id: 35, name: "Comedy", slug: "comedy" },
      { id: 878, name: "Sci-Fi", slug: "sci-fi" },
    ],
    runtime: 128,
  },
  {
    id: "movie-823464",
    tmdbId: 823464,
    imdbId: "tt14539740",
    type: "movie",
    title: "Godzilla x Kong: The New Empire",
    overview:
      "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world.",
    posterUrl: "https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/qrGtVFxaD8c7et0j3sjYne7Ux0Z.jpg",
    releaseDate: "2024-03-29",
    year: 2024,
    rating: 7.2,
    voteCount: 3300,
    genres: [
      { id: 28, name: "Action", slug: "action" },
      { id: 878, name: "Sci-Fi", slug: "sci-fi" },
      { id: 12, name: "Adventure", slug: "adventure" },
    ],
    runtime: 115,
  },
  {
    id: "movie-945961",
    tmdbId: 945961,
    imdbId: "tt11315808",
    type: "movie",
    title: "Alien: Romulus",
    overview:
      "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    posterUrl: "https://image.tmdb.org/t/p/w500/b33nnKl12cG4XYIC6iTyEGv3a9P.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    releaseDate: "2024-08-16",
    year: 2024,
    rating: 7.3,
    voteCount: 2200,
    genres: [
      { id: 27, name: "Horror", slug: "horror" },
      { id: 878, name: "Sci-Fi", slug: "sci-fi" },
    ],
    runtime: 119,
  },
  {
    id: "movie-157336",
    tmdbId: 157336,
    imdbId: "tt0816692",
    type: "movie",
    title: "Interstellar",
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/rAiYTsqLi0t04QwpZqoP0v8D9Um.jpg",
    releaseDate: "2014-11-05",
    year: 2014,
    rating: 8.4,
    voteCount: 34500,
    genres: [
      { id: 12, name: "Adventure", slug: "adventure" },
      { id: 18, name: "Drama", slug: "drama" },
      { id: 878, name: "Sci-Fi", slug: "sci-fi" },
    ],
    runtime: 169,
    director: "Christopher Nolan",
  },
  {
    id: "movie-1184918",
    tmdbId: 1184918,
    imdbId: "tt29454157",
    type: "movie",
    title: "Toofan",
    overview:
      "A young orphan grows into a ruthless and feared gangster named Galib, rising through the dark criminal underworld of 1990s Bangladesh.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8d8H0G1B0cZ63U5F1R3n3zJ5rA7.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/p9Z0hX8n8rD9jD5wL2k5vK9gQ8y.jpg",
    releaseDate: "2024-06-17",
    year: 2024,
    rating: 7.9,
    voteCount: 180,
    genres: [
      { id: 28, name: "Action", slug: "action" },
      { id: 80, name: "Crime", slug: "crime" },
      { id: 18, name: "Drama", slug: "drama" },
    ],
    runtime: 145,
    director: "Raihan Rafi",
  },
  {
    id: "movie-872585",
    tmdbId: 872585,
    imdbId: "tt15354916",
    type: "movie",
    title: "Jawan",
    overview:
      "An emotional journey of a prison warden driven by a personal vendetta while keeping a promise made years ago, standing against corruption and injustice.",
    posterUrl: "https://image.tmdb.org/t/p/w500/jNQ9wFm8KzV4u4U7c2E0qF4b4yA.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    releaseDate: "2023-09-07",
    year: 2023,
    rating: 7.3,
    voteCount: 290,
    genres: [
      { id: 28, name: "Action", slug: "action" },
      { id: 53, name: "Thriller", slug: "thriller" },
      { id: 18, name: "Drama", slug: "drama" },
    ],
    runtime: 169,
    director: "Atlee",
  },
  {
    id: "movie-579974",
    tmdbId: 579974,
    imdbId: "tt8178634",
    type: "movie",
    title: "RRR",
    overview:
      "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
    posterUrl: "https://image.tmdb.org/t/p/w500/nEufeZlyAOLqO2brrs0yeMu1QXO.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/70Rm9MzvhwZ6L0qHj71jW2eP6F7.jpg",
    releaseDate: "2022-03-24",
    year: 2022,
    rating: 7.8,
    voteCount: 1650,
    genres: [
      { id: 28, name: "Action", slug: "action" },
      { id: 18, name: "Drama", slug: "drama" },
    ],
    runtime: 187,
    director: "S.S. Rajamouli",
  },
];

export const MOCK_TRENDING_TV: TVShow[] = [
  {
    id: "tv-94605",
    tmdbId: 94605,
    imdbId: "tt11198330",
    type: "tv",
    title: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne.",
    posterUrl: "https://image.tmdb.org/t/p/w500/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    releaseDate: "2022-08-21",
    year: 2022,
    rating: 8.4,
    voteCount: 4300,
    genres: [
      { id: 10765, name: "Sci-Fi & Fantasy", slug: "sci-fi-fantasy" },
      { id: 18, name: "Drama", slug: "drama" },
      { id: 10759, name: "Action & Adventure", slug: "action-adventure" },
    ],
    totalSeasons: 2,
    totalEpisodes: 18,
  },
  {
    id: "tv-1396",
    tmdbId: 1396,
    imdbId: "tt0903747",
    type: "tv",
    title: "Breaking Bad",
    overview:
      "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years left to live. He chooses to enter a dangerous world of crime and produces the finest methamphetamine in the market.",
    posterUrl: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/9faGSFi5jam6pDWGNd0p8J2vMFQ.jpg",
    releaseDate: "2008-01-20",
    year: 2008,
    rating: 8.9,
    voteCount: 14000,
    genres: [
      { id: 18, name: "Drama", slug: "drama" },
      { id: 80, name: "Crime", slug: "crime" },
    ],
    totalSeasons: 5,
    totalEpisodes: 62,
  },
  {
    id: "tv-93405",
    tmdbId: 93405,
    imdbId: "tt10872600",
    type: "tv",
    title: "Squid Game",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
    posterUrl: "https://image.tmdb.org/t/p/w500/dDlGikw17vg6s8442Xg3fN0bOQk.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/2meX1nMdScFOoV4370rqHWKm5oY.jpg",
    releaseDate: "2021-09-17",
    year: 2021,
    rating: 7.8,
    voteCount: 13800,
    genres: [
      { id: 10759, name: "Action & Adventure", slug: "action-adventure" },
      { id: 9648, name: "Mystery", slug: "mystery" },
      { id: 18, name: "Drama", slug: "drama" },
    ],
    totalSeasons: 2,
    totalEpisodes: 15,
  },
];

export const MOCK_SEASON_1: Season = {
  id: "season-1",
  seasonNumber: 1,
  name: "Season 1",
  overview: "The inaugural season introducing the epic conflict and legendary characters.",
  episodeCount: 4,
  episodes: [
    {
      id: "ep-1",
      episodeNumber: 1,
      seasonNumber: 1,
      title: "The Heirs of the Dragon",
      overview: "Viserys hosts a tournament to celebrate the birth of his second child.",
      stillUrl: "https://image.tmdb.org/t/p/w300/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
      runtime: 66,
      voteAverage: 8.5,
    },
    {
      id: "ep-2",
      episodeNumber: 2,
      seasonNumber: 1,
      title: "The Rogue Prince",
      overview: "Rhaenyra disrupts the Small Council. Viserys is urged to secure the succession through marriage.",
      stillUrl: "https://image.tmdb.org/t/p/w300/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
      runtime: 54,
      voteAverage: 8.3,
    },
    {
      id: "ep-3",
      episodeNumber: 3,
      seasonNumber: 1,
      title: "Second of His Name",
      overview: "Daemon and the Sea Snake battle the Crabfeeder. The realm celebrates Aegon's second nameday.",
      stillUrl: "https://image.tmdb.org/t/p/w300/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
      runtime: 63,
      voteAverage: 8.6,
    },
    {
      id: "ep-4",
      episodeNumber: 4,
      seasonNumber: 1,
      title: "King of the Narrow Sea",
      overview: "Daemon cuts his campaign short. Rhaenyra returns to King's Landing to choose a consort.",
      stillUrl: "https://image.tmdb.org/t/p/w300/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
      runtime: 63,
      voteAverage: 8.4,
    },
  ],
};

